# Generated by Django 5.0.7 on 2024-08-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('recepcionista', 'Recepcionista'), ('hóspede', 'Hóspede')], default='recepcionista', max_length=50),
        ),
    ]
