# Generated by Django 5.0.7 on 2024-08-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zip_code',
            new_name='zipCode',
        ),
        migrations.RenameField(
            model_name='personaldata',
            old_name='document_number',
            new_name='documentNumber',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='qr_code',
            new_name='qrQode',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='qr_code_status',
            new_name='qrQodeStatus',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_date',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='personal_data',
            new_name='personalData',
        ),
    ]
