# Generated by Django 5.0.7 on 2024-08-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_description_alter_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='payment_status',
        ),
    ]
