# Generated by Django 5.1 on 2024-08-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_reservation_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checkedOut',
            field=models.BooleanField(default=False),
        ),
    ]
