# Generated by Django 5.1 on 2024-08-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reservation_checkedout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='qrQodeStatus',
            new_name='qrCodeStatus',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='qrQode',
        ),
        migrations.AddField(
            model_name='reservation',
            name='qrCode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
